### ISSUE TITLE
Manually grant root permissions

### ISSUE THREAD

**Issue by Roker2** [Akilesh-T/ACC#1]
Hi! I manually added root permissions and I could not create accent. After reinstall apk and grant root permission via pop-up menu, it is worked.
Sorry, but I didn't save logs.

**Comment by Akilesh-T** [comment]
> Hi! I manually added root permissions and I could not create accent. After reinstall apk and grant root permission via pop-up menu, it is worked.
> Sorry, but I didn't save logs.

Share the logs if you face it again.

**Comment by Akilesh-T** [comment]
Reopen this if you face the issue again.
