### ISSUE TITLE
Separate accent colors for light and dark modes

### ISSUE THREAD

**Issue by Jnss98b** [Akilesh-T/ACC#2]
The predefined accent colors in Android 10's developer options are desaturated when dark mode is enabled. It would be great if it's possible to pair separate light mode and dark mode accent colors within a single accent overlay with this app to simulate that.

**Comment by Akilesh-T** [comment]
There was an option to set different colours for light & dark themes till v1.10. [It'll be back. ](https://forum.xda-developers.com/showpost.php?p=81269417&postcount=56)

**Comment by Jnss98b** [comment]
Yeah I found out about that on the XDA thread. Anyways, this listing could help keep track of its progress I guess

**Comment by Jnss98b** [comment]
Also when this feature comes out, will it work on Android 9 with Night mode in developer options enabled?

**Comment by Akilesh-T** [comment]
> Yeah I found out about that on the XDA thread. Anyways, this listing could help keep track of its progress I guess

Yeah, will be useful to keep track of things.

> Also when this feature comes out, will it work on Android 9 with Night mode in developer options enabled?

Should work. Try [v1.10](https://github.com/Akilesh-T/ACC/releases/download/v1.10/qacc-v1.10.apk) if you wanna check.

**Comment by Jnss98b** [comment]
Sounds great. I'm looking forward to it

**Comment by Akilesh-T** [comment]
> Also when this feature comes out, will it work on Android 9 with Night mode in developer options enabled?

When “night mode” is turned on in Android 9 dark theme is applied only to _certain layouts_ like the QS panel. Hence, the dark theme's accent colour is applied only to those layouts and the rest use light theme's accent colour(as they are in light theme). There'll be two accents at the same time, making the UI inconsistent. So I'm planning to make this feature available only for Android 10, which has a proper system wide dark theme.

Here's a screenshot from Pie with dark theme turned on, in which [blue is dark theme's accent](https://user-images.githubusercontent.com/30697738/71912739-14b09f00-319c-11ea-86a4-4fc93758164f.jpg) & [orange is for light](https://user-images.githubusercontent.com/30697738/71912722-0d899100-319c-11ea-9e3d-644c399265ea.jpg).
