### ISSUE TITLE
UI Glitches and suggested solution

### ISSUE THREAD

**Issue by VarunS2002** [Akilesh-T/ACC#25]
ACC stores the overlay apks to `system/vendor/overlay/`.
However this causes UI glitches in some ROMs/ Devices like crDroid ROM Android 11 on Poco X3 Pro.
I manually created a Magisk module to place the ACC generated apk files to `system/vendor/overlay/` and found that the issue still persists.

I also manually created a Magisk module to place the ACC generated apk files to `system/product/overlay/`  (which is where crDroid has the default accent color overlay apk files) with a different naming convention and found that it works perfectly.
New naming convention: `system/product/overlay/ACCBlue/ACCBlue.apk` assuming that the name of the accent color is ACCBlue.
 I contacted the devs and this doesn't seem to be a ROM issue.
My suggestion to solve this issue:
1, One way is to dynamically detect the ideal location to store the overlay files. I do not know how this can be done. (Maybe check where the default accent color overlay apks are stored?)
2. Easier method is to allow the user to choose the location in Advanced settings and add a disclaimer to use that feature only when having issues.

The glitch is that the Brightness slider is broken completely giving random brightness values at any point in the slider.

[Glitch Video](https://imgur.com/a/iWiJNXq)
[logs-2021-06-23-11-19-33.zip](https://github.com/Akilesh-T/ACC/files/6721691/logs-2021-06-23-11-19-33.zip)

**Comment by Akilesh-T** [comment]
On 10+, overlays are pushed to product. 
https://github.com/Akilesh-T/ACC/blob/4b50a91ce149b103ebb2345738dce4dc461b6c43/app/src/main/java/app/akilesh/qacc/Const.kt#L432

If the latest version doesn't have it, wait for next release, but idk when as I don't have a working laptop now.
