### ISSUE TITLE
Accent color preference had been removed in latest AOSP release

### ISSUE THREAD

**Issue by seasonyuu** [Akilesh-T/ACC#3]
Accent color preference had been removed in latest AOSP release. And now I can only create accent colors instead of choosing them, would you add a chooser in your app?

**Comment by Akilesh-T** [comment]
> Accent color preference had been removed in latest AOSP release. And now I can only create accent colors instead of choosing them, would you add a chooser in your app?

By choosing do you mean enabling the accent?

If your device is a Pixel, Google moved it from developer options to styles and wallpaper. 

Either way, you can already enable or disable accents from the app.

**Comment by seasonyuu** [comment]
> > Accent color preference had been removed in latest AOSP release. And now I can only create accent colors instead of choosing them, would you add a chooser in your app?
> 
> By choosing do you mean enabling the accent?
> 
> If your device is a Pixel, Google moved it from developer options to styles and wallpaper.
> 
> Either way, you can already enable or disable accents from the app.

I'm using Essential Phone, When I click the "ENABLE" button, nothing happened
